name: device_preview_example
description: A simple demonstration of device_preview.
publish_to: none

version: 2.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets:
  cupertino_icons:
  flutter_localizations:
    sdk: flutter
  intl:
  device_preview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter 
  pedantic:

flutter:
  uses-material-design: true 