name: device_preview
version: 0.6.2-beta
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.7.0 <3.0.0' 

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  path_provider: ^2.0.1
  device_frame:
    path: ../device_frame
  font_awesome_flutter: ^9.0.0-nullsafety
  http: ^0.13.0 
  freezed_annotation: ^0.14.0
  json_annotation: ^4.0.0 
  meta: ^1.3.0 
  shared_preferences: ^2.0.3
  pedantic: ^1.11.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  build_runner: ^1.10.2
  freezed: ^0.14.0+1
  json_serializable:
  analyzer: ^1.1.0
